let citas = [
    {'autor': 'Douglas Bullet', 'texto': 'No importa cuántas veces me derroten, mientras siga respirando, no pienso rendirme.'},
    {'autor': 'Albert Einstein','texto': 'La imaginación es más importante que el conocimiento.'},
    {'autor': 'Mark Twain','texto': 'Nunca dejes que la verdad se interponga en el camino de una buena historia.'},
    {'autor': 'Nelson Mandela','texto': 'La educación es el arma más poderosa que puedes usar para cambiar el mundo.'},
    {'autor': 'Martin Luther King Jr.', 'texto': 'La oscuridad no puede expulsar a la oscuridad solo el amor puede hacerlo.'},
    {'autor': 'Monkey D. Luffy','texto': 'Mis amigos están aquí y ellos cuentan conmigo.'},
    {'autor': 'Pablo Picasso','texto': 'La inspiración existe, pero tiene que encontrarte trabajando.'},
    {'autor': 'Walt Disney', 'texto': 'La forma de empezar es dejar de hablar y comenzar a hacer.'},
    {'autor': 'Monkey D. Luffy','texto': '¡No habrías podido llegar tan lejos solo, te olvidas de quienes te ayudaron!.'},
    {'autor': 'Douglas Bullet', 'texto': 'Soy fuerte, porque confie en mi mismo.'},
    {'autor': 'J.K. Rowling','texto': 'La valentía no siempre ruge. A veces es la voz tranquila al final del día que dice: "Lo intentaré de nuevo mañana".'},
    {'autor': 'Vincent van Gogh','texto': 'Si amas la vida, la vida te amará de vuelta.'},
    {'autor': 'Douglas Bullet', 'texto': 'Solo la convicción y la fe en ti mismo pueden salvarte en la lucha.'},
    {'autor': 'Helen Keller','texto': 'La vida es una aventura audaz o no es nada.'},
    {'autor': 'Roronoa Zoro', 'texto': 'No me importa lo que la sociedad diga de mí. Nunca voy a hacer nada que vaya en contra de mis valores y de lo que después pueda arrepentirme'},
    {'autor': 'Ralph Waldo Emerson','texto': 'No sigas donde el camino puede llevar. Ve en cambio donde no hay camino y deja un rastro.'},
    {'autor': 'Roronoa Zoro', 'texto':'No pierde quién más veces cae, si no aquel que renuncia a levantarse.'},
    {'autor': 'Monkey D. Luffy', 'texto': 'Alguien que no tiene sueños no puede destruir los sueños de los demás.'},
    {'autor': 'Donquixote Doflamingo', 'texto':'Hay una diferencia en la mirada de un vagabundo y la de un hombre con propósito.'},
    {'autor': 'Trafalgar D. Law', 'texto': 'Hay cosas que no podrás ver a menos que cambies tu postura.'},
    {'autor': 'Monkey D. Garp', 'texto': 'La verdadera fuerza no proviene de la habilidad física, sino de la voluntad inquebrantable.'},
    {'autor': 'Vinsmoke Sanji', 'texto': 'La gente no puede elegir cómo nace, pero puede elegir cómo vivir.'},
    {'autor': 'Portgas D. Ace', 'texto': 'No importa cuánto tiempo pase, siempre habrá personas que quieran proteger a sus amigos.'},
    {'autor': 'Roronoa Zoro', 'texto': 'La gente no puede ganar sin sacrificarse.'},
    {'autor': 'Trafalgar D. Law', 'texto': 'La verdadera justicia viene de la voluntad del corazón.'},
    {'autor': 'Gol D. Roger', 'texto': 'La verdadera aventura comienza cuando algo sale mal.'},
    {'autor': 'Donquixote Doflamingo', 'texto': 'Los niños que nunca han visto la paz y los niños que nunca han visto la guerra tienen valores diferentes.'},
    {'autor': 'Marshall D. Teach', 'texto': 'No hay una recompensa sin riesgo.'},
    {'autor': 'Marshall D. Teach', 'texto': 'No importa lo fuerte que seas, no puedes llevar el mundo sobre tus hombros solo.'},
    {'autor': 'Douglas Bullet', 'texto': 'La verdadera justicia surge cuando nos levantamos después de cada caída.'},
];
